name: license_generator_example
description: A project used to demo the Todo Reporter
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  fast_barcode_scanner:
    git:
      url: git@github.com:vanlooverenkoen/fast_barcode_scanner.git
      ref: 0054f100f47f85da39d8cd6bab5eddbe21515d84
      path: fast_barcode_scanner
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  license_generator:
    path: ../
  test: ^1.17.10

flutter:
  assets:
    - assets/locale/

license_generator:
  #  fail_fast: true
  check_before_generate: true
  licenses:
  #    license_generator: https://raw.githubusercontent.com/icapps/flutter-icapps-license/master/LICENSE
  extra_licenses:
    something_something:
      name: Something Something
      version: 2.0.0
      homepage: https://www.google.com
      license: test_license
    license_generator:
      name: license_generator
      license: https://raw.githubusercontent.com/icapps/flutter-icapps-license/master/LICENSE
