name: icapps_license_example
description: A project used to demo the Todo Reporter
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^5.0.0
  shared_preferences: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  icapps_license:
    path: ../

flutter:
  assets:
    - assets/locale/

icapps_license:
  failFast: true
  licenses:
    icapps_license: 'https://raw.githubusercontent.com/icapps/flutter-icapps-license/master/LICENSE'