name: license_generator
description: Dart tool to generate a file that contains all licenses of the third party libraries
version: 3.0.0
homepage: https://github.com/icapps/flutter-icapps-license

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.1
  meta: ^1.3.0
  path: ^1.8.0
  yaml: ^3.1.0

dev_dependencies:
  flutter_lints: ^1.0.4
  test: ^1.16.8
