name: license_generator
description: Dart tool to generate a file that contains all licenses of the third party libraries
version: 2.0.0
homepage: https://github.com/icapps/flutter-icapps-license

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^1.0.0
  meta: ^1.9.1
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  flutter_lints: ^2.0.1
  test: ^1.24.3
